name: Build

on: [push]

env:
  BUILD_TYPE: MinSizeRel

jobs: 
  # === Windows PRO ===
  windows-pro:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Build
        shell: cmd
        run: |
          cd build
          cmake -G "Visual Studio 16 2019" -DBUILD_SDLGPU=On -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DBUILD_PRO=On ..
          cmake --build . --config %BUILD_TYPE% --parallel

      - name: Deploy
        uses: actions/upload-artifact@v3
        with:
          name: "tic80-windows-pro"
          path: build/bin/tic80.exe